# Generated by Django 4.2.20 on 2025-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Company's Name")),
                ('product_name', models.CharField(max_length=255, verbose_name="Product's Name")),
                ('picture', models.ImageField(max_length=255, upload_to='creatines', verbose_name='Picture')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, verbose_name='Discount')),
                ('size', models.CharField(default=200, max_length=4, verbose_name='Size')),
                ('link', models.URLField(verbose_name='Link')),
                ('partner_id', models.CharField(max_length=255, verbose_name='Partner ID')),
            ],
        ),
    ]
