# Generated by Django 4.2.20 on 2025-04-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creatineproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
