# Generated by Django 4.2.20 on 2025-04-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatineproduct',
            name='size',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('500', '500'), ('1000', '1000')], default=200, max_length=4, verbose_name='Size'),
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_water_intake', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Max Water Intake')),
                ('user_water_intake', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='User Water Intake')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
