# Generated by Django 4.2.20 on 2025-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='user_water_intake',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, verbose_name='User Water Intake'),
        ),
    ]
