# Generated by Django 4.2.20 on 2025-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterconsumption',
            name='user_water_intake',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='User Water Intake'),
        ),
    ]
