# Generated by Django 4.2.20 on 2025-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_waterconsumption_user_water_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatineproduct',
            name='description',
            field=models.TextField(blank=True, default='', max_length=355, null=True, verbose_name='Description'),
        ),
    ]
