# Generated by Django 4.2.20 on 2025-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_creatineproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatineproduct',
            name='size',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('400', '400'), ('500', '500'), ('1000', '1000')], default=200, max_length=4, verbose_name='Size'),
        ),
    ]
