# Generated by Django 4.2.20 on 2025-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_creatineproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatineproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Discount'),
        ),
    ]
