# Generated by Django 4.2.20 on 2025-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_creatineproduct_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=8, null=True, verbose_name='activity'),
        ),
    ]
